import type { Product } from '@/types';

export type ProductDetail = Product & {
  features: string[];
  specifications: Record<string, string>;
};

const baseProductsCatalog: ProductDetail[] = [
  // CÉSPED
  {
    id: '1',
    name: 'Césped Esmeralda m²',
    slug: 'cesped-esmeralda',
    description:
      'Césped de alta densidad y color intenso, ideal para jardines residenciales en Paraguay y zonas de alto tránsito moderado.',
    shortDescription: 'Césped natural premium para jardines en Paraguay',
    pricePerM2: 31000,
    unit: 'm2',
    minQuantity: 1,
    priceTiers: [
      { min: 1, max: 25, price: 48000, label: '1 a 25 m²' },
      { min: 26, max: 50, price: 43000, label: '26 a 50 m²' },
      { min: 51, max: null, price: 31000, label: 'Más de 50 m²', isPromo: true },
    ],
    images: [],
    category: 'cesped-natural',
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    features: [
      'Color verde uniforme',
      'Recuperación rápida',
      'Ideal para Asunción y Gran Asunción',
      'Bajo mantenimiento',
    ],
    specifications: {
      Tipo: 'Césped natural',
      Presentación: 'm²',
      Resistencia: 'Alta',
      Uso: 'Residencial y comercial',
    },
  },
  {
    id: '2',
    name: 'Césped Siempre Verde m²',
    slug: 'cesped-siempre-verde',
    description:
      'Variedad versátil con excelente adaptación al clima cálido, recomendada para cobertura uniforme durante todo el año.',
    shortDescription: 'Cobertura verde constante para jardines familiares',
    pricePerM2: 25000,
    unit: 'm2',
    minQuantity: 1,
    priceTiers: [
      { min: 1, max: 25, price: 38000, label: '1 a 25 m²' },
      { min: 26, max: 50, price: 34000, label: '26 a 50 m²' },
      { min: 51, max: null, price: 25000, label: 'Más de 50 m²', isPromo: true },
    ],
    images: [],
    category: 'cesped-natural',
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    features: [
      'Alta adaptabilidad',
      'Textura agradable',
      'Crecimiento uniforme',
      'Buena tolerancia al sol',
    ],
    specifications: {
      Tipo: 'Césped natural',
      Presentación: 'm²',
      Resistencia: 'Media/Alta',
      Uso: 'Residencial',
    },
  },
  {
    id: '3',
    name: 'Césped Kavaju m²',
    slug: 'cesped-kavaju',
    description:
      'Alternativa de césped rústico de rápida implantación, pensado para áreas extensas y proyectos de alto uso.',
    shortDescription: 'Césped rústico de gran cobertura',
    pricePerM2: 25000,
    unit: 'm2',
    minQuantity: 1,
    priceTiers: [
      { min: 1, max: 25, price: 38000, label: '1 a 25 m²' },
      { min: 26, max: 50, price: 34000, label: '26 a 50 m²' },
      { min: 51, max: null, price: 25000, label: 'Más de 50 m²', isPromo: true },
    ],
    images: [],
    category: 'cesped-natural',
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    features: [
      'Rápida implantación',
      'Cobertura amplia',
      'Buena resistencia',
      'Mantenimiento simple',
    ],
    specifications: {
      Tipo: 'Césped natural',
      Presentación: 'm²',
      Resistencia: 'Alta',
      Uso: 'Zonas amplias',
    },
  },
  {
    id: '4',
    name: 'Césped Maní por Docena',
    slug: 'cesped-mani-docena',
    description:
      'Planta tapizante ornamental ideal para cubrir espacios decorativos y bordes verdes de bajo porte.',
    shortDescription: 'Tapizante ornamental por docena',
    pricePerM2: 18000,
    unit: 'docena',
    minQuantity: 1,
    images: [],
    category: 'ornamentales',
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    features: [
      'Formato por docena',
      'Cobertura decorativa',
      'Bajo porte',
      'Ideal para canteros',
    ],
    specifications: {
      Tipo: 'Planta tapizante',
      Presentación: 'Docena',
      Resistencia: 'Media',
      Uso: 'Decorativo',
    },
  },

  // RIEGO AUTOMÁTICO
  {
    id: '13',
    name: 'Mini Rotor Rain Bird 3500',
    slug: 'mini-rotor-rain-bird-3500',
    description:
      'Mini rotor para cobertura uniforme en jardines medianos, con regulación de alcance y sector.',
    shortDescription: 'Mini rotor para riego técnico',
    pricePerM2: 76000,
    unit: 'unidad',
    minQuantity: 1,
    images: [],
    category: 'riego',
    isActive: true,
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    features: [
      'Ajuste de alcance',
      'Cobertura uniforme',
      'Marca Rain Bird',
      'Uso residencial/comercial',
    ],
    specifications: {
      Tipo: 'Mini rotor',
      Marca: 'Rain Bird',
      Modelo: '3500',
      Uso: 'Riego automático',
    },
  },
  {
    id: '12',
    name: 'Difusor de Riego',
    slug: 'difusor-riego',
    description:
      'Difusor para cobertura en zonas de jardinería de pequeño y mediano tamaño.',
    shortDescription: 'Cobertura puntual para canteros y césped',
    pricePerM2: 55000,
    unit: 'unidad',
    minQuantity: 1,
    images: [],
    category: 'riego',
    isActive: true,
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    features: [
      'Cobertura precisa',
      'Fácil ajuste',
      'Ideal para jardines',
      'Consumo eficiente',
    ],
    specifications: {
      Tipo: 'Difusor',
      Uso: 'Riego localizado',
      Cobertura: 'Baja/Media',
      Instalación: 'Simple',
    },
  },
  {
    id: '11',
    name: 'Válvula de Riego Rain Bird',
    slug: 'valvula-riego-rain-bird',
    description:
      'Válvula para control de sectores de riego con excelente desempeño y confiabilidad.',
    shortDescription: 'Control de riego profesional',
    pricePerM2: 89000,
    unit: 'unidad',
    minQuantity: 1,
    images: [],
    category: 'riego',
    isActive: true,
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    features: [
      'Control por sectores',
      'Alta confiabilidad',
      'Instalación estándar',
      'Baja mantención',
    ],
    specifications: {
      Tipo: 'Válvula',
      Marca: 'Rain Bird',
      Uso: 'Sistemas de riego',
      Presión: 'Media/Alta',
    },
  },
  {
    id: '10',
    name: 'Aspersor Rain Bird 5004',
    slug: 'aspersor-rain-bird-5004',
    description:
      'Aspersor de alto rendimiento para sistemas de riego residencial y comercial con cobertura uniforme.',
    shortDescription: 'Riego eficiente con marca líder',
    pricePerM2: 105000,
    unit: 'unidad',
    minQuantity: 1,
    images: [],
    category: 'riego',
    isActive: true,
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    features: [
      'Cobertura uniforme',
      'Regulación precisa',
      'Durabilidad Rain Bird',
      'Ideal para césped',
    ],
    specifications: {
      Tipo: 'Aspersor',
      Marca: 'Rain Bird',
      Modelo: '5004',
      Uso: 'Riego automático',
    },
  },

  // PAISAJISMO / DECORACIÓN
  {
    id: '8',
    name: 'Piso Ecológico 40x60',
    slug: 'piso-ecologico-40x60',
    description:
      'Piso drenante para senderos y zonas verdes, con formato 40x60 para proyectos residenciales y comerciales.',
    shortDescription: 'Piso drenante para espacios exteriores',
    pricePerM2: 85000,
    unit: 'm2',
    minQuantity: 1,
    images: [],
    category: 'pisos-exteriores',
    isActive: true,
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    features: [
      'Formato 40x60',
      'Permite drenaje',
      'Alta durabilidad',
      'Acabado moderno',
    ],
    specifications: {
      Tipo: 'Piso ecológico',
      Formato: '40x60',
      Uso: 'Exterior',
      Resistencia: 'Alta',
    },
  },
  {
    id: '7',
    name: 'Separador de Césped y Caminos',
    slug: 'separador-cesped-caminos',
    description:
      'Perfil separador para definir bordes entre césped, canteros y caminos con un acabado profesional.',
    shortDescription: 'Bordes prolijos para jardinería',
    pricePerM2: 25000,
    unit: 'unidad',
    minQuantity: 2,
    images: [],
    category: 'insumos-jardin',
    isActive: true,
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    features: [
      'Instalación simple',
      'Borde definido',
      'Mayor orden visual',
      'Apto exterior',
    ],
    specifications: {
      Tipo: 'Separador',
      Presentación: 'Unidad/metro lineal',
      Material: 'Polímero resistente',
      Uso: 'Exterior',
    },
  },
  {
    id: '9',
    name: 'Pisos imitación madera',
    slug: 'pisos-imitacion-madera',
    description:
      'Solución estética para exteriores con aspecto madera y mayor resistencia a humedad y uso continuo.',
    shortDescription: 'Calidez de madera con resistencia exterior',
    pricePerM2: 97000,
    unit: 'm2',
    minQuantity: 1,
    images: [],
    category: 'pisos-exteriores',
    isActive: true,
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    features: [
      'Acabado símil madera',
      'Fácil limpieza',
      'Apto intemperie',
      'Aspecto premium',
    ],
    specifications: {
      Tipo: 'Piso exterior',
      Acabado: 'Imitación madera',
      Uso: 'Patios y senderos',
      Resistencia: 'Alta',
    },
  },
  {
    id: '5',
    name: 'Granza Blanca Fina Decorativa',
    slug: 'granza-blanca-fina-decorativa',
    description:
      'Piedra decorativa blanca para diseño de jardines modernos, senderos y terminaciones de paisajismo.',
    shortDescription: 'Terminación decorativa premium',
    pricePerM2: 45000,
    unit: 'm2',
    minQuantity: 2,
    images: [],
    category: 'decorativos',
    isActive: true,
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    features: [
      'Color blanco fino',
      'Acabado elegante',
      'Bajo mantenimiento',
      'Ideal para contraste',
    ],
    specifications: {
      Tipo: 'Piedra decorativa',
      Presentación: 'Bolsa/por m²',
      Uso: 'Paisajismo',
      Origen: 'Paraguay',
    },
  },
  {
    id: '6',
    name: 'Canto Rodado',
    slug: 'canto-rodado',
    description:
      'Piedra redondeada para drenajes, decoración de jardines y terminaciones en zonas de alto tránsito.',
    shortDescription: 'Piedra versátil para jardín y paisajismo',
    pricePerM2: 42000,
    unit: 'm2',
    minQuantity: 2,
    images: [],
    category: 'decorativos',
    isActive: true,
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    features: [
      'Buena drenabilidad',
      'Aspecto natural',
      'Alta durabilidad',
      'Uso múltiple',
    ],
    specifications: {
      Tipo: 'Piedra decorativa',
      Presentación: 'Bolsa/por m²',
      Uso: 'Jardín y drenaje',
      Acabado: 'Natural',
    },
  },

  // SERVICIOS
  {
    id: '14',
    name: 'Servicio mantenimiento de jardín',
    slug: 'servicio-mantenimiento-jardin',
    description:
      'Servicio periódico de mantenimiento para conservar césped, canteros y sistema de riego en óptimas condiciones.',
    shortDescription: 'Mantenimiento integral en Asunción y alrededores',
    pricePerM2: 150000,
    unit: 'visita',
    minQuantity: 1,
    images: [],
    category: 'servicios',
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    features: [
      'Visita técnica',
      'Plan de mantenimiento',
      'Control preventivo',
      'Cobertura en Asunción',
    ],
    specifications: {
      Tipo: 'Servicio',
      Modalidad: 'Por visita',
      Cobertura: 'Asunción y Gran Asunción',
      Incluye: 'Evaluación y tareas de mantenimiento',
    },
  },
];

// función automática de imágenes
const withImages = (product: ProductDetail): ProductDetail => ({
  ...product,
  images:
    product.images && product.images.length > 0
      ? product.images
      : [`/productos/${product.slug}.jpg`],
});

// catálogo final con imágenes automáticas
export const productsCatalog: ProductDetail[] = baseProductsCatalog.map(withImages);

export const productsData: Record<string, ProductDetail> = Object.fromEntries(
  productsCatalog.map((product) => [product.slug, product])
);

export const defaultProduct: ProductDetail = {
  id: '0',
  name: 'Producto Corpicia',
  slug: 'producto-corpicia',
  description: 'Descripción del producto',
  shortDescription: 'Producto disponible en Corpicia',
  pricePerM2: 0,
  unit: 'm2',
  minQuantity: 1,
  images: ['/productos/default.jpg'],
  category: 'general',
  isActive: true,
  isFeatured: false,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  features: [],
  specifications: {},
};

export const productCategories = [
  { id: 'all', name: 'Todos', slug: 'all' },
  { id: 'cesped-natural', name: 'Césped Natural', slug: 'cesped-natural' },
  { id: 'ornamentales', name: 'Ornamentales', slug: 'ornamentales' },
  { id: 'decorativos', name: 'Decorativos', slug: 'decorativos' },
  { id: 'insumos-jardin', name: 'Insumos de Jardín', slug: 'insumos-jardin' },
  { id: 'pisos-exteriores', name: 'Pisos Exteriores', slug: 'pisos-exteriores' },
  { id: 'riego', name: 'Riego', slug: 'riego' },
  { id: 'servicios', name: 'Servicios', slug: 'servicios' },
];
