export const productsData: Record<string, any> = {
  'cesped-esmeralda-premium': {
    id: '1',
    name: 'Césped Esmeralda Premium',
    slug: 'cesped-esmeralda-premium',
    description: 'El Césped Esmeralda Premium es la elección perfecta para quienes buscan un jardín de aspecto impecable y de alta resistencia. Este tipo de césped se caracteriza por su color verde intenso, textura fina y capacidad de recuperación rápida.',
    shortDescription: 'Césped premium de alta resistencia',
    pricePerM2: 31000,
    minQuantity: 10,
    images: [],
    category: 'cesped',
    isActive: true,
    isFeatured: true,
    features: [
      'Color verde intenso todo el año',
      'Alta resistencia al pisoteo',
      'Rápido crecimiento y recuperación',
      'Ideal para climas cálidos',
      'Bajo mantenimiento requerido',
    ],
    specifications: {
      Tipo: 'Césped natural',
      Origen: 'Paraguay',
      Resistencia: 'Alta',
      Mantenimiento: 'Medio',
      Crecimiento: 'Rápido',
    },
  },
  'cesped-bermuda': {
    id: '2',
    name: 'Césped Bermuda',
    slug: 'cesped-bermuda',
    description: 'El Césped Bermuda es conocido por su extraordinaria resistencia a la sequía y su capacidad de mantenerse verde incluso en las condiciones más adversas. Perfecto para áreas con alto tránsito.',
    shortDescription: 'Ideal para climas cálidos',
    pricePerM2: 28000,
    minQuantity: 15,
    images: [],
    category: 'cesped',
    isActive: true,
    isFeatured: true,
    features: [
      'Extrema resistencia a la sequía',
      'Ideal para climas cálidos',
      'Excelente para áreas deportivas',
      'Recuperación rápida',
      'Bajo consumo de agua',
    ],
    specifications: {
      Tipo: 'Césped natural',
      Origen: 'Híbrido',
      Resistencia: 'Muy Alta',
      Mantenimiento: 'Bajo',
      Crecimiento: 'Rápido',
    },
  },
};

export const defaultProduct = {
  id: '0',
  name: 'Producto',
  slug: 'producto',
  description: 'Descripción del producto',
  shortDescription: '',
  pricePerM2: 0,
  minQuantity: 10,
  images: [],
  category: 'general',
  isActive: true,
  isFeatured: false,
  features: [],
  specifications: {},
};
