import type { Product } from '@/types';

export type ProductDetail = Product & {
  features: string[];
  specifications: Record<string, string>;
  relatedSlugs?: string[];
};

export const productsCatalog: ProductDetail[] = [
  {
    id: '1',
    name: 'Césped Esmeralda m²',
    slug: 'cesped-esmeralda',
    description: 'Césped de alta densidad y color intenso, ideal para jardines residenciales en Paraguay y zonas de alto tránsito moderado.',
    shortDescription: 'Césped natural premium para jardines en Paraguay',
    pricePerM2: 32000,
    unit: 'm2',
    minQuantity: 10,
    priceTiers: [
      { min: 10, max: 24, price: 36000, label: '10 a 24 m²' },
      { min: 25, max: 49, price: 34000, label: '25 a 49 m²' },
      { min: 50, max: null, price: 32000, label: '50+ m²', isPromo: true },
    ],
    images: [],
    category: 'cesped-natural',
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    features: ['Color verde uniforme', 'Recuperación rápida', 'Ideal para Asunción y Gran Asunción', 'Bajo mantenimiento'],
    relatedSlugs: ['cesped-siempre-verde', 'cesped-kavaju', 'servicio-mantenimiento-jardin', 'mini-rotor-rain-bird-3500'],
    specifications: {
      Tipo: 'Césped natural',
      Presentación: 'm²',
      Resistencia: 'Alta',
      Uso: 'Residencial y comercial',
    },
  },
  {
    id: '2',
    name: 'Césped Siempre Verde m²',
    slug: 'cesped-siempre-verde',
    description: 'Variedad versátil con excelente adaptación al clima cálido, recomendada para cobertura uniforme durante todo el año.',
    shortDescription: 'Cobertura verde constante para jardines familiares',
    pricePerM2: 30000,
    unit: 'm2',
    minQuantity: 10,
    priceTiers: [
      { min: 10, max: 24, price: 34000, label: '10 a 24 m²' },
      { min: 25, max: 49, price: 32000, label: '25 a 49 m²' },
      { min: 50, max: null, price: 30000, label: '50+ m²', isPromo: true },
    ],
    images: [],
    category: 'cesped-natural',
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    features: ['Alta adaptabilidad', 'Textura agradable', 'Crecimiento uniforme', 'Buena tolerancia al sol'],
    relatedSlugs: ['cesped-esmeralda', 'cesped-kavaju', 'servicio-mantenimiento-jardin', 'difusor-riego'],
    specifications: {
      Tipo: 'Césped natural',
      Presentación: 'm²',
      Resistencia: 'Media/Alta',
      Uso: 'Residencial',
    },
  },
  {
    id: '3',
    name: 'Césped Kavaju m²',
    slug: 'cesped-kavaju',
    description: 'Alternativa de césped rústico de rápida implantación, pensado para áreas extensas y proyectos de alto uso.',
    shortDescription: 'Césped rústico de gran cobertura',
    pricePerM2: 28000,
    unit: 'm2',
    minQuantity: 15,
    priceTiers: [
      { min: 15, max: 29, price: 32000, label: '15 a 29 m²' },
      { min: 30, max: 59, price: 30000, label: '30 a 59 m²' },
      { min: 60, max: null, price: 28000, label: '60+ m²', isPromo: true },
    ],
    images: [],
    category: 'cesped-natural',
    isActive: true,
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    features: ['Rápida implantación', 'Cobertura amplia', 'Buena resistencia', 'Mantenimiento simple'],
    relatedSlugs: ['cesped-esmeralda', 'cesped-siempre-verde', 'servicio-mantenimiento-jardin', 'aspersor-rain-bird-5004'],
    specifications: {
      Tipo: 'Césped natural',
      Presentación: 'm²',
      Resistencia: 'Alta',
      Uso: 'Zonas amplias',
    },
  },
  {
    id: '4',
    name: 'Césped Maní por Docena',
    slug: 'cesped-mani-docena',
    description: 'Planta tapizante ornamental ideal para cubrir espacios decorativos y bordes verdes de bajo porte.',
    shortDescription: 'Tapizante ornamental por docena',
    pricePerM2: 18000,
    unit: 'docena',
    minQuantity: 1,
    images: [],
    category: 'ornamentales',
    isActive: true,
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    features: ['Formato por docena', 'Cobertura decorativa', 'Bajo porte', 'Ideal para canteros'],
    relatedSlugs: ['granza-blanca-fina-decorativa', 'canto-rodado', 'separador-cesped-caminos'],
    specifications: {
      Tipo: 'Planta tapizante',
      Presentación: 'Docena',
      Resistencia: 'Media',
      Uso: 'Decorativo',
    },
  },
  {
    id: '5',
    name: 'Granza Blanca Fina Decorativa',
    slug: 'granza-blanca-fina-decorativa',
    description: 'Piedra decorativa blanca para diseño de jardines modernos, senderos y terminaciones de paisajismo.',
    shortDescription: 'Terminación decorativa premium',
    pricePerM2: 45000,
    unit: 'm2',
    minQuantity: 2,
    images: [],
    category: 'decorativos',
    isActive: true,
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    features: ['Color blanco fino', 'Acabado elegante', 'Bajo mantenimiento', 'Ideal para contraste'],
    relatedSlugs: ['canto-rodado', 'separador-cesped-caminos', 'piso-ecologico-40x60'],
    specifications: {
      Tipo: 'Piedra decorativa',
      Presentación: 'Bolsa/por m²',
      Uso: 'Paisajismo',
      Origen: 'Paraguay',
    },
  },
  {
    id: '6',
    name: 'Canto Rodado',
    slug: 'canto-rodado',
    description: 'Piedra redondeada para drenajes, decoración de jardines y terminaciones en zonas de alto tránsito.',
    shortDescription: 'Piedra versátil para jardín y paisajismo',
    pricePerM2: 42000,
    unit: 'm2',
    minQuantity: 2,
    images: [],
    category: 'decorativos',
    isActive: true,
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    features: ['Buena drenabilidad', 'Aspecto natural', 'Alta durabilidad', 'Uso múltiple'],
    relatedSlugs: ['granza-blanca-fina-decorativa', 'piso-ecologico-40x60', 'separador-cesped-caminos'],
    specifications: {
      Tipo: 'Piedra decorativa',
      Presentación: 'Bolsa/por m²',
      Uso: 'Jardín y drenaje',
      Acabado: 'Natural',
    },
  },
  {
    id: '7',
    name: 'Separador de Césped y Caminos',
    slug: 'separador-cesped-caminos',
    description: 'Perfil separador para definir bordes entre césped, canteros y caminos con un acabado profesional.',
    shortDescription: 'Bordes prolijos para jardinería',
    pricePerM2: 25000,
    unit: 'unidad',
    minQuantity: 2,
    images: [],
    category: 'insumos-jardin',
    isActive: true,
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    features: ['Instalación simple', 'Borde definido', 'Mayor orden visual', 'Apto exterior'],
    relatedSlugs: ['granza-blanca-fina-decorativa', 'canto-rodado', 'pisos-imitacion-madera'],
    specifications: {
      Tipo: 'Separador',
      Presentación: 'Unidad/metro lineal',
      Material: 'Polímero resistente',
      Uso: 'Exterior',
    },
  },
  {
    id: '8',
    name: 'Piso Ecológico 40x60',
    slug: 'piso-ecologico-40x60',
    description: 'Piso drenante para senderos y zonas verdes, con formato 40x60 para proyectos residenciales y comerciales.',
    shortDescription: 'Piso drenante para espacios exteriores',
    pricePerM2: 85000,
    unit: 'm2',
    minQuantity: 1,
    images: [],
    category: 'pisos-exteriores',
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    features: ['Formato 40x60', 'Permite drenaje', 'Alta durabilidad', 'Acabado moderno'],
    relatedSlugs: ['pisos-imitacion-madera', 'granza-blanca-fina-decorativa', 'separador-cesped-caminos'],
    specifications: {
      Tipo: 'Piso ecológico',
      Formato: '40x60',
      Uso: 'Exterior',
      Resistencia: 'Alta',
    },
  },
  {
    id: '9',
    name: 'Pisos imitación madera',
    slug: 'pisos-imitacion-madera',
    description: 'Solución estética para exteriores con aspecto madera y mayor resistencia a humedad y uso continuo.',
    shortDescription: 'Calidez de madera con resistencia exterior',
    pricePerM2: 97000,
    unit: 'm2',
    minQuantity: 1,
    images: [],
    category: 'pisos-exteriores',
    isActive: true,
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    features: ['Acabado símil madera', 'Fácil limpieza', 'Apto intemperie', 'Aspecto premium'],
    relatedSlugs: ['piso-ecologico-40x60', 'granza-blanca-fina-decorativa', 'canto-rodado'],
    specifications: {
      Tipo: 'Piso exterior',
      Acabado: 'Imitación madera',
      Uso: 'Patios y senderos',
      Resistencia: 'Alta',
    },
  },
  {
    id: '10',
    name: 'Aspersor Rain Bird 5004',
    slug: 'aspersor-rain-bird-5004',
    description: 'Aspersor de alto rendimiento para sistemas de riego residencial y comercial con cobertura uniforme.',
    shortDescription: 'Riego eficiente con marca líder',
    pricePerM2: 105000,
    unit: 'unidad',
    minQuantity: 1,
    images: [],
    category: 'riego',
    isActive: true,
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    features: ['Cobertura uniforme', 'Regulación precisa', 'Durabilidad Rain Bird', 'Ideal para césped'],
    relatedSlugs: ['valvula-riego-rain-bird', 'mini-rotor-rain-bird-3500', 'difusor-riego'],
    specifications: {
      Tipo: 'Aspersor',
      Marca: 'Rain Bird',
      Modelo: '5004',
      Uso: 'Riego automático',
    },
  },
  {
    id: '11',
    name: 'Válvula de Riego Rain Bird',
    slug: 'valvula-riego-rain-bird',
    description: 'Válvula para control de sectores de riego con excelente desempeño y confiabilidad.',
    shortDescription: 'Control de riego profesional',
    pricePerM2: 89000,
    unit: 'unidad',
    minQuantity: 1,
    images: [],
    category: 'riego',
    isActive: true,
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    features: ['Control por sectores', 'Alta confiabilidad', 'Instalación estándar', 'Baja mantención'],
    relatedSlugs: ['aspersor-rain-bird-5004', 'mini-rotor-rain-bird-3500', 'difusor-riego'],
    specifications: {
      Tipo: 'Válvula',
      Marca: 'Rain Bird',
      Uso: 'Sistemas de riego',
      Presión: 'Media/Alta',
    },
  },
  {
    id: '12',
    name: 'Difusor de Riego',
    slug: 'difusor-riego',
    description: 'Difusor para cobertura en zonas de jardinería de pequeño y mediano tamaño.',
    shortDescription: 'Cobertura puntual para canteros y césped',
    pricePerM2: 55000,
    unit: 'unidad',
    minQuantity: 1,
    images: [],
    category: 'riego',
    isActive: true,
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    features: ['Cobertura precisa', 'Fácil ajuste', 'Ideal para jardines', 'Consumo eficiente'],
    relatedSlugs: ['aspersor-rain-bird-5004', 'valvula-riego-rain-bird', 'mini-rotor-rain-bird-3500'],
    specifications: {
      Tipo: 'Difusor',
      Uso: 'Riego localizado',
      Cobertura: 'Baja/Media',
      Instalación: 'Simple',
    },
  },
  {
    id: '13',
    name: 'Mini Rotor Rain Bird 3500',
    slug: 'mini-rotor-rain-bird-3500',
    description: 'Mini rotor para cobertura uniforme en jardines medianos, con regulación de alcance y sector.',
    shortDescription: 'Mini rotor para riego técnico',
    pricePerM2: 76000,
    unit: 'unidad',
    minQuantity: 1,
    images: [],
    category: 'riego',
    isActive: true,
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    features: ['Ajuste de alcance', 'Cobertura uniforme', 'Marca Rain Bird', 'Uso residencial/comercial'],
    relatedSlugs: ['aspersor-rain-bird-5004', 'valvula-riego-rain-bird', 'difusor-riego'],
    specifications: {
      Tipo: 'Mini rotor',
      Marca: 'Rain Bird',
      Modelo: '3500',
      Uso: 'Riego automático',
    },
  },
  {
    id: '14',
    name: 'Servicio mantenimiento de jardín',
    slug: 'servicio-mantenimiento-jardin',
    description: 'Servicio periódico de mantenimiento para conservar césped, canteros y sistema de riego en óptimas condiciones.',
    shortDescription: 'Mantenimiento integral en Asunción y alrededores',
    pricePerM2: 150000,
    unit: 'visita',
    minQuantity: 1,
    images: [],
    category: 'servicios',
    isActive: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    features: ['Visita técnica', 'Plan de mantenimiento', 'Control preventivo', 'Cobertura en Asunción'],
    relatedSlugs: ['cesped-esmeralda', 'cesped-siempre-verde', 'cesped-kavaju', 'mini-rotor-rain-bird-3500'],
    specifications: {
      Tipo: 'Servicio',
      Modalidad: 'Por visita',
      Cobertura: 'Asunción y Gran Asunción',
      Incluye: 'Evaluación y tareas de mantenimiento',
    },
  },
];

export const productsData: Record<string, ProductDetail> = Object.fromEntries(
  productsCatalog.map((product) => [product.slug, product])
);

export const defaultProduct: ProductDetail = {
  id: '0',
  name: 'Producto Corpicia',
  slug: 'producto-corpicia',
  description: 'Descripción del producto',
  shortDescription: 'Producto disponible en Corpicia',
  pricePerM2: 0,
  unit: 'm2',
  minQuantity: 1,
  images: [],
  category: 'general',
  isActive: true,
  isFeatured: false,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  features: [],
  specifications: {},
};

export const productCategories = [
  { id: 'all', name: 'Todos', slug: 'all' },
  { id: 'cesped-natural', name: 'Césped Natural', slug: 'cesped-natural' },
  { id: 'ornamentales', name: 'Ornamentales', slug: 'ornamentales' },
  { id: 'decorativos', name: 'Decorativos', slug: 'decorativos' },
  { id: 'insumos-jardin', name: 'Insumos de Jardín', slug: 'insumos-jardin' },
  { id: 'pisos-exteriores', name: 'Pisos Exteriores', slug: 'pisos-exteriores' },
  { id: 'riego', name: 'Riego', slug: 'riego' },
  { id: 'servicios', name: 'Servicios', slug: 'servicios' },
];

export function getRelatedProducts(product: ProductDetail, limit = 4): ProductDetail[] {
  const relatedBySlug = (product.relatedSlugs || [])
    .map((slug) => productsData[slug])
    .filter((item): item is ProductDetail => Boolean(item) && item.slug !== product.slug);

  if (relatedBySlug.length >= limit) {
    return relatedBySlug.slice(0, limit);
  }

  const categoryFallback = productsCatalog.filter(
    (item) =>
      item.slug !== product.slug &&
      item.category === product.category &&
      !relatedBySlug.some((related) => related.slug === item.slug)
  );

  const mixedFallback = productsCatalog.filter(
    (item) =>
      item.slug !== product.slug &&
      !relatedBySlug.some((related) => related.slug === item.slug) &&
      !categoryFallback.some((fallback) => fallback.slug === item.slug)
  );

  return [...relatedBySlug, ...categoryFallback, ...mixedFallback].slice(0, limit);
}
